### ISSUE TITLE
Selector not working for nested elements

### ISSUE THREAD

**Issue by bjoern-vsc** [zirbest/unocss-preset-primitives#10]
This is a great plugin - but the variant seems to only work on HTML elements that themselves get the data-headlessui-state attributes. It would be really nice to apply it to all children as well ([just like the TailwindCSS does](https://github.com/tailwindlabs/headlessui/blob/main/packages/%40headlessui-tailwindcss/src/index.ts)) so I can do something like this:

```
<HeadlessDisclosure>
    <HeadlessDisclosureButton>
        <ins class="ui-open:i-tabler-x ui-closed:i-tabler-settings"  />
    </HeadlessDisclosureButton>
    <HeadlessDisclosurePanel>
        <p>Lorem Ipsum</p>
    </HeadlessDisclosurePanel>
</HeadlessDisclosure>
```

**Comment by zirbest** [comment]
done  [v0.0.1-beta.9](https://github.com/zirbest/unocss-preset-primitives/releases/tag/v0.0.1-beta.9)

**Comment by bjoern-reetz** [comment]
Big thanks!
