### ISSUE TITLE
Kobalte styling is not working

### ISSUE THREAD

**Issue by andrewdoro** [zirbest/unocss-preset-primitives#2]
https://github.com/zirbest/unocss-preset-primitives/blob/bef9fd1b130c7c4855acb19b5792236b2e783762/src/index.ts#L37-L39
I am newbie to Unocss, but only if I replace the `~='` with a simple `-` makes it work with Kobalte Componets.
```
 selector: (s: any) =>
              match[1] === "-not"
                ? `${s}[${selector}]:not([${selector}-${match[2]}])`
                : `${s}[${selector}-${match[2]}]`,
```

**Comment by zirbest** [comment]
thnx @andrewdoro
fixed in [v0.0.1-beta.5](https://github.com/zirbest/unocss-preset-primitives/releases/tag/v0.0.1-beta.5)
